### ISSUE TITLE
experiments with CN3065 charging module

### ISSUE THREAD

**Issue by morrowwm** [gbhug5a/Solar-Power-Load-Sharing#2]
Inspired by the discussion over on eevblog, I tried your idea with a CN3065 based charger, [like this].  (https://www.amazon.com/Charger-Lithium-Battery-Application-Charging/dp/B07KNVBYRL).

Solar panel into CN3065, battery out and "system out" to a 2 schottky diode power path decider, which outputs to the real load, a  3.3V Arduino Pro Mini. Partial schematic attached, showing the Arduino as a load resistor.

The idea is the output of the solar panel goes straight to the load when it's high enough, so the load does not interfere with charging the battery according to the CN3065's scheme. When the panel power drops below the battery voltage, the battery takes over powering the load.

After some time, I think related to the solar panel power dropping (i.e. at night), the Arduino will go into a strange constant rebooting state. Disconnecting power gets it going OK again. Voltage as measured with a meter is fine, and the drops across D1 and D2 make sense. 

I do have a 220 uF capacitor across the load's power rails, thinking that would help smooth out the transition between states. Maybe that's actually enabling some oscillation?

![cn3065_power_path](https://user-images.githubusercontent.com/11416685/222513892-fd3702da-74ca-434a-8e3f-5fe5c81f76f2.png)
![power_path_pic](https://user-images.githubusercontent.com/11416685/222517682-84f5436c-379c-4cf8-aeb4-51c04b649e11.jpeg)

**Comment by gbhug5a** [comment]
Sorry I didn't respond when you posted this.  I guess I need to check for issues more often.

I don't know what would cause the Arduino to go into a boot loop.  The schottky diode produces a 0.3V drop, but even so, the Pro Mini shouldn't drop out.  But it almost has to be something like that - some power issure that's causing a brownout.
